version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: final_image
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env 
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - mern-network
    depends_on:
      - backend  
    env_file:
      - ./frontend/.env

networks:
  mern-network:
    driver: bridge

    # docker-compose up --build -d

