version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mern-network     

  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env 
    networks:
      - mern-network
    depends_on:
      - mongo  

  frontend:
    container_name: frontend
    build: ./frontend 
    restart: unless-stopped  
    ports:
      - "5173:5173"
    networks:
      - mern-network
    depends_on:
      - backend  
    env_file:
      - ./frontend/.env  
       

networks:
  mern-network:
    driver: bridge
    # docker-compose up --build -d

